"use client";

/**
 * 优效营统一图标库
 * 基于 Phosphor Icons 构建
 * 提供统一的图标组件和使用规范
 * 
 * 使用指南：
 * 1. 基础图标：import { Plus, Trash } from "@/components/icons"
 * 2. 语义化图标：import { Icons } from "@/components/icons"
 *    使用：Icons.action.create, Icons.nav.home
 * 3. 图标组件：import { Icon, ButtonIcon } from "@/components/ui/icon"
 * 4. 配置：import { ICON_SIZES, ICON_WEIGHTS } from "@/components/icons/config"
 */

import type { Icon as PhosphorIcon } from "@phosphor-icons/react";
import {
  // Navigation & Layout
  House,
  Bell,
  Users,
  Package,
  Coins,
  ClipboardText,
  Robot,
  Gear,
  List,
  X,
  CaretDown,
  CaretUp,
  CaretLeft,
  CaretRight,
  MagnifyingGlass,
  Plus,
  Minus,
  PencilSimple,
  Trash,
  Check,
  XCircle,
  CheckCircle,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  ArrowsClockwise,
  DotsThree,
  DotsThreeVertical,

  // Communication & User
  User,
  UserCircle,
  UsersThree,
  Envelope,
  Phone,
  ChatText,
  PaperPlane,
  ShareNetwork,
  Heart,
  Star,
  ThumbsUp,

  // Business & Finance
  CurrencyDollar,
  Receipt,
  Invoice,
  ChartLineUp,
  ChartPie,
  ChartBar,
  TrendUp,
  TrendDown,
  PiggyBank,
  CreditCard,
  Wallet,
  Money,
  Bank,
  Calculator,
  FileText,
  Files,
  Folder,
  FolderOpen,
  DownloadSimple,
  UploadSimple,
  Export,
  FileCsv,
  FilePdf,
  FileXls,
  Building,
  Tray,
  FileSearch,
  Activity,

  // Actions & States
  Eye,
  EyeSlash,
  Lock,
  LockOpen,
  Copy,
  Clipboard,
  Link,
  LinkBreak,
  Funnel,
  SortAscending,
  SortDescending,
  CaretUpDown,
  ArrowsVertical,
  ArrowLineUp,
  ArrowLineDown,
  MagnifyingGlassPlus,
  MagnifyingGlassMinus,

  // Alerts & Feedback
  Info,
  Warning,
  WarningCircle,
  WarningOctagon,
  Question,
  QuestionMark,
  Prohibit,
  Shield,
  ShieldCheck,
  ShieldWarning,
  Crosshair,
  CrosshairSimple,

  // Time & Calendar
  Calendar,
  CalendarCheck,
  CalendarPlus,
  CalendarX,
  CalendarBlank,
  Clock,
  ClockCounterClockwise,
  Timer,
  Hourglass,
  Alarm,

  // Inventory & Operations
  Truck,
  Storefront,
  Barcode,
  QrCode,
  Scales,
  Tag,
  Archive,
  ArchiveBox,
  Cube,
  Stack,

  // AI & Technology
  Brain,
  Sparkle,
  MagicWand,
  Scan,
  Aperture,
  Camera,
  Image,
  FileImage,
  Paperclip,

  // System & Device
  Desktop,
  Laptop,
  DeviceMobile,
  Printer,
  HardDrives,
  Database,
  Cloud,
  CloudArrowUp,
  CloudArrowDown,
  WifiHigh,
  Sun,
  Moon,

  // Editor & Content
  TextAa,
  TextT,
  ListBullets,
  ListNumbers,
  TextAlignLeft,
  TextAlignCenter,
  TextAlignRight,
  Quotes,
  Code,
  Highlighter,
  TextB,

  // Misc
  Crown,
  Trophy,
  Medal,
  Flag,
  FlagBanner,
  MapPin,
  NavigationArrow,
  Compass,
  Globe,
  GlobeHemisphereWest,
  Translate,
  BookOpen,
  BookBookmark,
  GraduationCap,
  Student,
  ChalkboardTeacher,
  Exam,

  // Spinners & Loading
  Spinner,
  SpinnerGap,
} from "@phosphor-icons/react";

// Icon weight type
export type Icon = PhosphorIcon;

export type IconWeight = "thin" | "light" | "regular" | "bold" | "fill" | "duotone";

// ==================== Lucide to Phosphor 映射 ====================
/**
 * 从 Lucide Icons 迁移到 Phosphor Icons 的映射表
 * 用于帮助快速替换现有图标
 */
export const LucideToPhosphor: Record<string, string> = {
  // Navigation
  "Home": "House",
  "Bell": "Bell",
  "Users": "Users",
  "Package": "Package",
  "Coins": "Coins",
  "ClipboardList": "ClipboardText",
  "Bot": "Robot",
  "Settings": "Gear",
  "Menu": "List",
  "X": "X",
  "ChevronDown": "CaretDown",
  "ChevronUp": "CaretUp",
  "ChevronLeft": "CaretLeft",
  "ChevronRight": "CaretRight",
  "Search": "MagnifyingGlass",
  "Plus": "Plus",
  "Trash2": "Trash",
  "Pencil": "PencilSimple",
  "BookOpen": "BookOpen",
  "ArrowLeft": "ArrowLeft",
  "ArrowRight": "ArrowRight",
  "Check": "Check",
  "CheckCircle2": "CheckCircle",
  "XCircle": "XCircle",
  "Clock": "Clock",
  "Clock4": "Clock",
  "RefreshCw": "ArrowsClockwise",
  "Loader2": "Spinner",
  "Calendar": "Calendar",
  "MapPin": "MapPin",
  "AlertCircle": "WarningCircle",
  "TrendingUp": "TrendingUp",
  "Briefcase": "ClipboardText",
  "Sparkles": "Sparkle",
  "AlertTriangle": "Warning",
  "TrendingDown": "TrendDown",
  "FileSpreadsheet": "FileXls",
  "FileText": "FileText",
  "Download": "DownloadSimple",
  "Receipt": "Receipt",
  "Edit": "PencilSimple",
  "Trash": "Trash",
  "MessageSquare": "ChatText",
  "Link2": "Link",
  "Phone": "Phone",
  "Mail": "Envelope",
  "Building2": "Building",
  "Crown": "Crown",
  "History": "ClockCounterClockwise",
  "User": "User",
};

// 直接导出所有图标，方便单独导入
export {
  House,
  Bell,
  Users,
  Package,
  Coins,
  ClipboardText,
  Robot,
  Gear,
  List,
  X,
  CaretDown,
  CaretUp,
  CaretLeft,
  CaretRight,
  MagnifyingGlass,
  Plus,
  Minus,
  PencilSimple,
  Trash,
  Check,
  XCircle,
  CheckCircle,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  ArrowsClockwise,
  DotsThree,
  DotsThreeVertical,
  User,
  UserCircle,
  UsersThree,
  Envelope,
  Phone,
  ChatText,
  PaperPlane,
  ShareNetwork,
  Heart,
  Star,
  ThumbsUp,
  CurrencyDollar,
  Receipt,
  Invoice,
  ChartLineUp,
  ChartPie,
  ChartBar,
  TrendUp,
  TrendDown,
  PiggyBank,
  CreditCard,
  Wallet,
  Money,
  Bank,
  Calculator,
  FileText,
  Files,
  Folder,
  FolderOpen,
  DownloadSimple,
  UploadSimple,
  Export,
  FileCsv,
  FilePdf,
  FileXls,
  Eye,
  EyeSlash,
  Lock,
  LockOpen,
  Copy,
  Clipboard,
  Link,
  LinkBreak,
  Funnel,
  SortAscending,
  SortDescending,
  CaretUpDown,
  ArrowsVertical,
  ArrowLineUp,
  ArrowLineDown,
  MagnifyingGlassPlus,
  MagnifyingGlassMinus,
  Info,
  Warning,
  WarningCircle,
  WarningOctagon,
  Question,
  QuestionMark,
  Prohibit,
  Shield,
  ShieldCheck,
  ShieldWarning,
  Crosshair,
  CrosshairSimple,
  Calendar,
  CalendarCheck,
  CalendarPlus,
  CalendarX,
  CalendarBlank,
  Clock,
  ClockCounterClockwise,
  Timer,
  Hourglass,
  Alarm,
  Truck,
  Storefront,
  Barcode,
  QrCode,
  Scales,
  Tag,
  Archive,
  ArchiveBox,
  Cube,
  Stack,
  Brain,
  Sparkle,
  MagicWand,
  Scan,
  Aperture,
  Camera,
  Image,
  FileImage,
  Paperclip,
  Desktop,
  Laptop,
  DeviceMobile,
  Printer,
  HardDrives,
  Database,
  Cloud,
  CloudArrowUp,
  CloudArrowDown,
  WifiHigh,
  Sun,
  Moon,
  TextAa,
  TextT,
  ListBullets,
  ListNumbers,
  TextAlignLeft,
  TextAlignCenter,
  TextAlignRight,
  Quotes,
  Code,
  Highlighter,
  TextB,
  Crown,
  Trophy,
  Medal,
  Flag,
  FlagBanner,
  MapPin,
  NavigationArrow,
  Compass,
  Globe,
  GlobeHemisphereWest,
  Translate,
  BookOpen,
  BookBookmark,
  GraduationCap,
  Student,
  ChalkboardTeacher,
  Exam,
  Spinner,
  SpinnerGap,
  Building,
  Tray,
  FileSearch,
  Activity,
};

// ==================== 重新导出配置和语义化图标 ====================
export {
  // 配置
  ICON_SIZES,
  ICON_WEIGHTS,
  ICON_COLORS,
  ICON_USAGE,
  DEFAULT_ICON_WEIGHT,
  ACTIVE_ICON_WEIGHT,
  SUBTLE_ICON_WEIGHT,
  getIconSize,
  getIconColor,
  getIconConfig,
} from "./config";

export type { IconSize, IconColor, IconWeightType } from "./config";

// 语义化图标
export {
  Icons,
  ActionIcons,
  NavIcons,
  UserIcons,
  CRMIcons,
  InventoryIcons,
  FinanceIcons,
  DocumentIcons,
  TimeIcons,
  StatusIcons,
  CommunicationIcons,
  AIIcons,
  SystemIcons,
  LoadingIcons,
} from "./semantic";

// 默认导出
const IconsExport = {
  LucideToPhosphor,
};
export default IconsExport;
